"""add_prompt5_workflow_fields

Revision ID: 6367209aeed1
Revises: 8f7ded40d108
Create Date: 2026-07-26 00:01:27.729949

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6367209aeed1'
down_revision: Union[str, None] = '8f7ded40d108'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email_summaries', sa.Column('requires_followup', sa.Boolean(), nullable=True, comment='If true, a background task will spawn a follow-up reminder on send'))
    op.add_column('reminders', sa.Column('google_task_id', sa.String(), nullable=True, comment='Linked Google Task ID for priority morphing'))
    op.add_column('reminders', sa.Column('google_event_id', sa.String(), nullable=True, comment='Linked Google Calendar Event ID for focus blocks'))
    op.add_column('reminders', sa.Column('task_type', sa.String(), nullable=True, comment="Type of task (e.g. 'follow_up', 'focus')"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reminders', 'task_type')
    op.drop_column('reminders', 'google_event_id')
    op.drop_column('reminders', 'google_task_id')
    op.drop_column('email_summaries', 'requires_followup')
    # ### end Alembic commands ###
