"""add_last_history_id_to_connected_accounts

Revision ID: a02feb254429
Revises: e2b74630a2a5
Create Date: 2026-07-04 12:36:53.941962

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a02feb254429'
down_revision: Union[str, None] = 'e2b74630a2a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('connected_accounts', sa.Column('last_history_id', sa.String(length=50), nullable=True, comment='Gmail historyId from the last incremental sync. Used to fetch only new changes.'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('connected_accounts', 'last_history_id')
    # ### end Alembic commands ###
