"""initial_tables

Revision ID: e2b74630a2a5
Revises: 
Create Date: 2026-06-26 15:47:27.766135

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e2b74630a2a5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('google_id', sa.String(length=255), nullable=False, comment='Google OAuth sub claim'),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('avatar_url', sa.String(length=2048), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_google_id'), 'users', ['google_id'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('agent_actions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('action_type', sa.String(length=100), nullable=False, comment="e.g. 'send_email', 'create_task', 'archive_email'"),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Structured action parameters (e.g. reply body, recipients)'),
    sa.Column('status', sa.String(length=50), nullable=False, comment='pending_approval | approved | rejected | executed | failed'),
    sa.Column('error_message', sa.String(length=2000), nullable=True, comment='Populated if status=failed'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_actions_id'), 'agent_actions', ['id'], unique=False)
    op.create_index(op.f('ix_agent_actions_user_id'), 'agent_actions', ['user_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True, comment='Null for system-level events'),
    sa.Column('event_type', sa.String(length=100), nullable=False, comment="e.g. 'user.login', 'email.fetched', 'action.approved', 'action.executed'"),
    sa.Column('event_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Arbitrary context data for this event'),
    sa.Column('ip_address', sa.String(length=45), nullable=True, comment='IPv4 or IPv6 address of the requester'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_event_type'), 'audit_logs', ['event_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('connected_accounts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False, comment="e.g. 'google', 'microsoft'"),
    sa.Column('provider_account_id', sa.String(length=255), nullable=False, comment="Provider's user/account ID"),
    sa.Column('access_token', sa.Text(), nullable=False),
    sa.Column('refresh_token', sa.Text(), nullable=True),
    sa.Column('scopes', postgresql.ARRAY(sa.String()), nullable=True, comment='Granted OAuth scopes'),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_connected_accounts_id'), 'connected_accounts', ['id'], unique=False)
    op.create_index(op.f('ix_connected_accounts_user_id'), 'connected_accounts', ['user_id'], unique=False)
    op.create_table('emails',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('gmail_id', sa.String(length=255), nullable=False, comment='Gmail message ID'),
    sa.Column('thread_id', sa.String(length=255), nullable=True, comment='Gmail thread ID'),
    sa.Column('sender', sa.String(length=320), nullable=False),
    sa.Column('sender_name', sa.String(length=255), nullable=True),
    sa.Column('recipient', sa.String(length=320), nullable=True),
    sa.Column('subject', sa.String(length=998), nullable=False),
    sa.Column('body_text', sa.Text(), nullable=True),
    sa.Column('body_html', sa.Text(), nullable=True),
    sa.Column('snippet', sa.String(length=500), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('is_processed', sa.Boolean(), nullable=False, comment='True when the AI agent has analysed this email'),
    sa.Column('labels', postgresql.ARRAY(sa.String()), nullable=True, comment='Gmail label IDs'),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_emails_gmail_id'), 'emails', ['gmail_id'], unique=True)
    op.create_index(op.f('ix_emails_id'), 'emails', ['id'], unique=False)
    op.create_index(op.f('ix_emails_thread_id'), 'emails', ['thread_id'], unique=False)
    op.create_index(op.f('ix_emails_user_id'), 'emails', ['user_id'], unique=False)
    op.create_table('memories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('key', sa.String(length=255), nullable=False, comment="Namespaced memory key, e.g. 'preferences.tone' or 'contacts.john_doe'"),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Arbitrary JSON value'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'key', name='uq_memory_user_key')
    )
    op.create_index(op.f('ix_memories_id'), 'memories', ['id'], unique=False)
    op.create_index(op.f('ix_memories_user_id'), 'memories', ['user_id'], unique=False)
    op.create_table('approvals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('agent_action_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False, comment='pending | approved | rejected'),
    sa.Column('feedback', sa.Text(), nullable=True, comment='Optional CEO note when approving or rejecting'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True, comment='When the CEO approved or rejected'),
    sa.ForeignKeyConstraint(['agent_action_id'], ['agent_actions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_approvals_agent_action_id'), 'approvals', ['agent_action_id'], unique=True)
    op.create_index(op.f('ix_approvals_id'), 'approvals', ['id'], unique=False)
    op.create_index(op.f('ix_approvals_user_id'), 'approvals', ['user_id'], unique=False)
    op.create_table('email_summaries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email_id', sa.UUID(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False, comment='Short AI-generated summary of the email'),
    sa.Column('category', sa.String(length=100), nullable=True, comment="e.g. 'invoice', 'inquiry', 'complaint', 'newsletter'"),
    sa.Column('sentiment', sa.String(length=50), nullable=True, comment="e.g. 'positive', 'negative', 'neutral'"),
    sa.Column('priority', sa.Integer(), nullable=False, comment='1=critical, 2=high, 3=medium, 4=low, 5=ignore'),
    sa.Column('action_required', sa.Boolean(), nullable=True, comment='Whether the AI recommends a response/action'),
    sa.Column('suggested_action', sa.Text(), nullable=True, comment="AI-suggested next action (e.g. 'Reply with quote')"),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['email_id'], ['emails.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_summaries_email_id'), 'email_summaries', ['email_id'], unique=True)
    op.create_index(op.f('ix_email_summaries_id'), 'email_summaries', ['id'], unique=False)
    op.create_table('tasks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('email_id', sa.UUID(), nullable=True, comment='Source email that triggered this task'),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False, comment='pending | in_progress | completed | cancelled'),
    sa.Column('priority', sa.String(length=20), nullable=False, comment='critical | high | medium | low'),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['email_id'], ['emails.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tasks_email_id'), 'tasks', ['email_id'], unique=False)
    op.create_index(op.f('ix_tasks_id'), 'tasks', ['id'], unique=False)
    op.create_index(op.f('ix_tasks_user_id'), 'tasks', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tasks_user_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_email_id'), table_name='tasks')
    op.drop_table('tasks')
    op.drop_index(op.f('ix_email_summaries_id'), table_name='email_summaries')
    op.drop_index(op.f('ix_email_summaries_email_id'), table_name='email_summaries')
    op.drop_table('email_summaries')
    op.drop_index(op.f('ix_approvals_user_id'), table_name='approvals')
    op.drop_index(op.f('ix_approvals_id'), table_name='approvals')
    op.drop_index(op.f('ix_approvals_agent_action_id'), table_name='approvals')
    op.drop_table('approvals')
    op.drop_index(op.f('ix_memories_user_id'), table_name='memories')
    op.drop_index(op.f('ix_memories_id'), table_name='memories')
    op.drop_table('memories')
    op.drop_index(op.f('ix_emails_user_id'), table_name='emails')
    op.drop_index(op.f('ix_emails_thread_id'), table_name='emails')
    op.drop_index(op.f('ix_emails_id'), table_name='emails')
    op.drop_index(op.f('ix_emails_gmail_id'), table_name='emails')
    op.drop_table('emails')
    op.drop_index(op.f('ix_connected_accounts_user_id'), table_name='connected_accounts')
    op.drop_index(op.f('ix_connected_accounts_id'), table_name='connected_accounts')
    op.drop_table('connected_accounts')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_event_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_agent_actions_user_id'), table_name='agent_actions')
    op.drop_index(op.f('ix_agent_actions_id'), table_name='agent_actions')
    op.drop_table('agent_actions')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_google_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
