"""add approval_status to email_summaries

Revision ID: f3b15efd06ad
Revises: a02feb254429
Create Date: 2026-07-20 11:05:19.917532

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3b15efd06ad'
down_revision: Union[str, None] = 'a02feb254429'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email_summaries', sa.Column('approval_status', sa.String(length=20), nullable=True, comment="User decision: 'pending' | 'approved' | 'rejected'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('email_summaries', 'approval_status')
    # ### end Alembic commands ###
